Yggdrasil Tray: SocketManager Class Reference
SocketManager Class Reference
Manages communication with a UNIX domain socket.
#include <SocketManager.h>
Public Member Functions
SocketManager (const QString &socketPath)
Constructs a SocketManager for the specified socket path.
QJsonObject sendRequest (const QJsonObject &request)
Sends a request to the socket and receives the response.
QString getYggdrasilIP ()
Retrieves the Yggdrasil IP address from the socket.
Private Attributes
QString socketPath
The path to the UNIX domain socket.
Detailed Description
Manages communication with a UNIX domain socket.
This class provides methods for sending requests to and receiving responses from a UNIX domain socket, as well as retrieving specific information such as the Yggdrasil IP address.
Definition at line 26 of file SocketManager.h.
Constructor & Destructor Documentation
SocketManager()
SocketManager::SocketManager (const QString & socketPath) inline explicit
Constructs a SocketManager for the specified socket path.
Parameters
socketPath The path to the UNIX domain socket.
Definition at line 32 of file SocketManager.h.
: socketPath(socketPath) {}
Member Function Documentation
getYggdrasilIP()
QString SocketManager::getYggdrasilIP () inline
Retrieves the Yggdrasil IP address from the socket.
Returns
A QString containing the IP address, or "Unknown" if an error occurred.
This method sends a "getself" request to the socket and parses the response to extract the IP address.
Definition at line 80 of file SocketManager.h.
{
        QJsonObject response = sendRequest({{"request", "getself"}});
        if (response.contains("response") && response["response"].isObject()) {
            return response["response"].toObject()["address"].toString();
        }
        return "Unknown";
    }
References sendRequest().
Referenced by YggdrasilTray::copyIP(), and YggdrasilTray::updateTrayIcon().
sendRequest()
QJsonObject SocketManager::sendRequest (const QJsonObject & request) inline
Sends a request to the socket and receives the response.
Parameters
request A QJsonObject containing the request data.
Returns
A QJsonObject containing the response, or an empty object if an error occurred.
This method handles connecting to the socket, sending the request, and reading the response. It logs any errors encountered during the process.
Definition at line 42 of file SocketManager.h.
{
        QLocalSocket socket;
        socket.connectToServer(socketPath);
        if (!socket.waitForConnected(3000)) {
            qDebug() << "Failed to connect to socket at" << socketPath;
            return {};
        }
        QByteArray requestData = QJsonDocument(request).toJson(QJsonDocument::Compact) + "\n";
        socket.write(requestData);
        if (!socket.waitForBytesWritten(3000)) {
            qDebug() << "Failed to write request to socket";
            return {};
        }
        if (!socket.waitForReadyRead(3000)) {
            qDebug() << "No response from socket";
            return {};
        }
        QByteArray responseData = socket.readAll();
        QJsonDocument responseDoc = QJsonDocument::fromJson(responseData);
        if (!responseDoc.isObject()) {
            qDebug() << "Invalid JSON response from socket";
            return {};
        }
        return responseDoc.object();
    }
References socketPath.
Referenced by getYggdrasilIP().
Member Data Documentation
socketPath
QString SocketManager::socketPath private
The path to the UNIX domain socket.
Definition at line 89 of file SocketManager.h.
Referenced by sendRequest().
The documentation for this class was generated from the following file:
SocketManager.h