Yggdrasil Tray: ServiceManager Class Reference
ServiceManager Class Reference
Handles system service management using systemctl commands.
#include <ServiceManager.h>
Public Member Functions
ServiceManager (const QString &serviceName)
Constructs a ServiceManager for the specified service.
bool isServiceRunning () const
Checks if the service is currently running.
bool startService () const
Starts the specified service.
bool stopService () const
Stops the specified service.
Private Member Functions
bool executeCommand (const QString &action) const
Executes a systemctl command for the specified action.
Private Attributes
QString serviceName
The name of the service to manage.
Detailed Description
Handles system service management using systemctl commands.
This class provides methods to check the status of a service, start a service, and stop a service using system commands.
Definition at line 22 of file ServiceManager.h.
Constructor & Destructor Documentation
ServiceManager()
ServiceManager::ServiceManager (const QString & serviceName) inline explicit
Constructs a ServiceManager for the specified service.
Parameters
serviceName The name of the service to manage.
Definition at line 28 of file ServiceManager.h.
: serviceName(serviceName) {}
Member Function Documentation
executeCommand()
bool ServiceManager::executeCommand (const QString & action) const inline private
Executes a systemctl command for the specified action.
Parameters
action The action to perform (e.g., "start" or "stop").
Returns
True if the command was successful, false otherwise.
This method uses pkexec to run the systemctl command with elevated privileges.
Definition at line 78 of file ServiceManager.h.
{
        QProcess process;
        QStringList arguments = {"systemctl", action, serviceName};
        process.start("pkexec", arguments);
        process.waitForFinished();
        if (process.exitCode() == 0) {
            qDebug() << action << "command executed successfully for" << serviceName;
            return true;
        } else {
            qDebug() << action << "command failed for" << serviceName << ":" << process.readAllStandardError();
            return false;
        }
    }
References serviceName.
Referenced by startService(), and stopService().
isServiceRunning()
bool ServiceManager::isServiceRunning () const inline
Checks if the service is currently running.
Returns
True if the service is running, false otherwise.
Uses the systemctl is-active command to determine the status of the specified service.
Definition at line 37 of file ServiceManager.h.
{
        QProcess process;
        QStringList arguments = {"is-active", serviceName};
        process.start("systemctl", arguments);
        process.waitForFinished();
        QString output = process.readAllStandardOutput().trimmed();
        return (output == "active");
    }
References serviceName.
Referenced by YggdrasilTray::toggleYggdrasilService(), and YggdrasilTray::updateTrayIcon().
startService()
bool ServiceManager::startService () const inline
Starts the specified service.
Returns
True if the service was started successfully, false otherwise.
Executes the systemctl start command using pkexec.
Definition at line 53 of file ServiceManager.h.
{
        return executeCommand("start");
    }
References executeCommand().
Referenced by YggdrasilTray::toggleYggdrasilService().
stopService()
bool ServiceManager::stopService () const inline
Stops the specified service.
Returns
True if the service was stopped successfully, false otherwise.
Executes the systemctl stop command using pkexec.
Definition at line 63 of file ServiceManager.h.
{
        return executeCommand("stop");
    }
References executeCommand().
Referenced by YggdrasilTray::toggleYggdrasilService().
Member Data Documentation
serviceName
QString ServiceManager::serviceName private
The name of the service to manage.
Definition at line 68 of file ServiceManager.h.
Referenced by executeCommand(), and isServiceRunning().
The documentation for this class was generated from the following file:
ServiceManager.h