Yggdrasil Tray: YggdrasilTray Class Reference
YggdrasilTray Class Reference
Manages the system tray interface for the Yggdrasil service.
Public Member Functions
YggdrasilTray (QObject *parent=nullptr)
Constructs the YggdrasilTray object.
Private Slots
void toggleYggdrasilService ()
Toggles the Yggdrasil service between running and stopped states.
void copyIP ()
Copies the Yggdrasil IP address to the clipboard.
void updateTrayIcon ()
Updates the tray icon and menu items.
void onTrayIconActivated (QSystemTrayIcon::ActivationReason reason)
Handles tray icon activation events.
Private Attributes
QSystemTrayIcon * trayIcon
The system tray icon.
QMenu * trayMenu
The menu displayed in the system tray.
QAction * statusAction
Action displaying the service status.
QAction * ipAction
Action displaying the Yggdrasil IP address.
QAction * toggleAction
Action to toggle the Yggdrasil service.
QAction * copyIPAction
Action to copy the Yggdrasil IP address.
ServiceManager serviceManager
Manager for service-related tasks.
SocketManager socketManager
Manager for socket-related tasks.
Detailed Description
Manages the system tray interface for the Yggdrasil service.
This class handles GUI interactions, service toggling, and updates the tray icon based on the Yggdrasil service status.
Definition at line 48 of file tray.cpp.
Constructor & Destructor Documentation
YggdrasilTray()
YggdrasilTray::YggdrasilTray (QObject * parent = nullptr) inline explicit
Constructs the YggdrasilTray object.
Parameters
parent Pointer to the parent QObject, if any.
Definition at line 56 of file tray.cpp.
        : QObject(parent),
          serviceManager("yggdrasil"),
          socketManager(YGG_SOCKET_PATH) {
        trayIcon = new QSystemTrayIcon(this);
        trayIcon->setIcon(QIcon::fromTheme(ICON_NOT_RUNNING));
        trayIcon->setToolTip(TOOLTIP);
        trayMenu = new QMenu();
        // Status menu item
        statusAction = new QAction("Status: Unknown", trayMenu);
        statusAction->setDisabled(true);
        trayMenu->addAction(statusAction);
        // IP address menu item
        ipAction = new QAction("IP: Unknown", trayMenu);
        ipAction->setDisabled(true);
        trayMenu->addAction(ipAction);
        trayMenu->addSeparator();
        // Toggle Yggdrasil service action
        toggleAction = new QAction("Start/Stop Yggdrasil", trayMenu);
        connect(toggleAction, &QAction::triggered, this, &YggdrasilTray::toggleYggdrasilService);
        trayMenu->addAction(toggleAction);
        // Copy IP action
        copyIPAction = new QAction("Copy IP", trayMenu);
        connect(copyIPAction, &QAction::triggered, this, &YggdrasilTray::copyIP);
        trayMenu->addAction(copyIPAction);
        trayMenu->addSeparator();
        // Quit action
        QAction *quitAction = new QAction("Quit", trayMenu);
        connect(quitAction, &QAction::triggered, qApp, &QApplication::quit);
        trayMenu->addAction(quitAction);
        trayIcon->setContextMenu(trayMenu);
        trayIcon->show();
        // Connect activated signal
        connect(trayIcon, &QSystemTrayIcon::activated, this, &YggdrasilTray::onTrayIconActivated);
        // Periodic update
        QTimer *timer = new QTimer(this);
        connect(timer, &QTimer::timeout, this, &YggdrasilTray::updateTrayIcon);
        timer->start(5000);
        updateTrayIcon();
    }
References copyIP(), copyIPAction, ICON_NOT_RUNNING, ipAction, onTrayIconActivated(), statusAction, toggleAction, toggleYggdrasilService(), TOOLTIP, trayIcon, trayMenu, and updateTrayIcon().
Member Function Documentation
copyIP
void YggdrasilTray::copyIP () inline private slot
Copies the Yggdrasil IP address to the clipboard.
Retrieves the Yggdrasil IP address from the socket manager and copies it to the system clipboard. Displays a message indicating the result of the operation.
Definition at line 145 of file tray.cpp.
                  {
        QString ip = socketManager.getYggdrasilIP();
        if (!ip.isEmpty()) {
            QApplication::clipboard()->setText(ip);
            QMessageBox::information(nullptr, "Copy IP", "IP copied to clipboard: " + ip);
        } else {
            QMessageBox::warning(nullptr, "Copy IP", "Failed to retrieve IP.");
        }
    }
References SocketManager::getYggdrasilIP(), and socketManager.
Referenced by YggdrasilTray().
onTrayIconActivated
void YggdrasilTray::onTrayIconActivated (QSystemTrayIcon::ActivationReason reason) inline private slot
Handles tray icon activation events.
Parameters
reason The reason for the activation event.
Displays the tray menu when the tray icon is activated via a left or right click.
Definition at line 178 of file tray.cpp.
{
        if (reason == QSystemTrayIcon::Trigger || reason == QSystemTrayIcon::Context) {
            trayMenu->popup(QCursor::pos());
        }
    }
References trayMenu.
Referenced by YggdrasilTray().
toggleYggdrasilService
void YggdrasilTray::toggleYggdrasilService () inline private slot
Toggles the Yggdrasil service between running and stopped states.
This function checks the current status of the Yggdrasil service and either starts or stops it. It updates the tray icon and displays a message indicating the result of the operation.
Definition at line 117 of file tray.cpp.
{
        bool success;
        QString action;
        if (serviceManager.isServiceRunning()) {
            success = serviceManager.stopService();
            action = "stopped";
        } else {
            success = serviceManager.startService();
            action = "started";
        }
        if (success) {
            QMessageBox::information(nullptr, "Service Toggle", "Yggdrasil service successfully " + action + ".");
        } else {
            QMessageBox::critical(nullptr, "Service Toggle", "Failed to toggle Yggdrasil service.");
        }
        updateTrayIcon();
    }
References ServiceManager::isServiceRunning(), serviceManager, ServiceManager::startService(), ServiceManager::stopService(), and updateTrayIcon().
Referenced by YggdrasilTray().
updateTrayIcon
void YggdrasilTray::updateTrayIcon () inline private slot
Updates the tray icon and menu items.
Retrieves the current Yggdrasil service status and IP address, then updates the tray icon and menu items to reflect this information.
Definition at line 161 of file tray.cpp.
{
        QString status = serviceManager.isServiceRunning() ? "Running" : "Not Running";
        QString ip = socketManager.getYggdrasilIP();
        statusAction->setText("Status: " + status);
        ipAction->setText("IP: " + ip);
        trayIcon->setIcon(QIcon::fromTheme(status == "Running" ? ICON_RUNNING : ICON_NOT_RUNNING));
    }
References SocketManager::getYggdrasilIP(), ICON_NOT_RUNNING, ICON_RUNNING, ipAction, ServiceManager::isServiceRunning(), serviceManager, socketManager, statusAction, and trayIcon.
Referenced by toggleYggdrasilService(), and YggdrasilTray().
Member Data Documentation
copyIPAction
QAction* YggdrasilTray::copyIPAction private
Action to copy the Yggdrasil IP address.
Definition at line 190 of file tray.cpp.
Referenced by YggdrasilTray().
ipAction
QAction* YggdrasilTray::ipAction private
Action displaying the Yggdrasil IP address.
Definition at line 188 of file tray.cpp.
Referenced by updateTrayIcon(), and YggdrasilTray().
serviceManager
ServiceManager YggdrasilTray::serviceManager private
Manager for service-related tasks.
Definition at line 191 of file tray.cpp.
Referenced by toggleYggdrasilService(), and updateTrayIcon().
socketManager
SocketManager YggdrasilTray::socketManager private
Manager for socket-related tasks.
Definition at line 192 of file tray.cpp.
Referenced by copyIP(), and updateTrayIcon().
statusAction
QAction* YggdrasilTray::statusAction private
Action displaying the service status.
Definition at line 187 of file tray.cpp.
Referenced by updateTrayIcon(), and YggdrasilTray().
toggleAction
QAction* YggdrasilTray::toggleAction private
Action to toggle the Yggdrasil service.
Definition at line 189 of file tray.cpp.
Referenced by YggdrasilTray().
trayIcon
QSystemTrayIcon* YggdrasilTray::trayIcon private
The system tray icon.
Definition at line 185 of file tray.cpp.
Referenced by updateTrayIcon(), and YggdrasilTray().
trayMenu
QMenu* YggdrasilTray::trayMenu private
The menu displayed in the system tray.
Definition at line 186 of file tray.cpp.
Referenced by onTrayIconActivated(), and YggdrasilTray().
The documentation for this class was generated from the following file:
tray.cpp