name: Build and Release Yggtray

on:
  push:
    tags:
      - 'v*' # Trigger the workflow for version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual triggers

jobs:
  build:
    name: Build Yggtray
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Qt environment
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake cmake g++ make

      # Build the project
      - name: Build Project
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake ..
          make VERBOSE=1

      # Archive the built executable
      - name: Archive Executable
        run: |
          mkdir -p artifacts
          cp build/yggtray artifacts/yggtray
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: yggtray-executable
          path: artifacts/yggtray

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: yggtray-executable

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/yggtray
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automatic release for version ${{ github.ref_name }}.
            Built on GitHub Actions.

