name: Build and Release Yggdrasil Tray

on:
  push:
    tags:
      - "*" # Run only on tag pushes
  workflow_dispatch: # Allow manual triggering of the workflow (optional)

env:
  BUILD_TYPE: Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Extract the version from the Git tag
    - name: Get Version from Git Tag
      id: get_version
      run: |
        if [ -z "${{ github.ref_name }}" ]; then
          echo "No tag found. Exiting."
          exit 1
        fi
        echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    # Step 3: Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential qtbase5-dev qt5-qmake qttools5-dev

    # Step 4: Configure CMake
    - name: Configure CMake
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    # Step 5: Build the project
    - name: Build
      run: |
        cd build
        make VERBOSE=1

    # Step 6: Package the artifact
    - name: Package artifact
      run: |
        cd build
        tar -czvf yggtray-${{ env.VERSION }}.tar.gz yggtray

    # Step 7: Upload the artifact
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: yggtray
        path: build/yggtray-${{ env.VERSION }}.tar.gz

    # Step 8: Create Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Yggdrasil Tray v${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/yggtray-${{ env.VERSION }}.tar.gz
        asset_name: yggtray-${{ env.VERSION }}.tar.gz
        asset_content_type: application/gzip
